services:
  - type: worker
    name: telegram-neuro-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
