services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        value: <ТВОЙ_ТОКЕН>
      - key: WEBHOOK_URL
        value: <URL_БОТА>/webhook
